# Generated by Django 4.2 on 2023-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
