# Generated by Django 4.2 on 2023-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Kids', 'Kids'), ('Cars', 'Cars'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Games', 'Games'), ('Toys', 'Toys'), ('Sporting Goods', 'Sporting Goods'), ('Jwellary & Watches', 'Jwellary & Watches')], default='Unspecified', max_length=64),
        ),
    ]
