# Generated by Django 4.2 on 2023-04-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='User',
            new_name='user',
        ),
    ]
