# Generated by Django 4.2 on 2023-04-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_rename_user_command_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='bid_amount',
            new_name='amount',
        ),
    ]
